Feature/routing #2
Dev-FE-1/Toy_Project_3_Team5 pull request #37
Opened 2024-08-27 11:12 UTC by LfromTheE

# 🚀 풀 리퀘스트 제안

**[작업 내용을 간략히 적어주세요]**
라우팅 구조 배치
## 📋 작업 내용

1루트에 route 폴더에 route 로직 작성
2각 페이지의 폴더 구조 생성

수정한 내용이나 추가한 기능에 대해 자세히 설명해 주세요.

app파일에서 따로 뺏습니다.

## 🔧 변경 사항

주요 변경 사항을 요약해 주세요.

## 📸 스크린샷 (선택 사항)

수정된 화면 또는 기능을 시연할 수 있는 스크린샷을 첨부할 수 있습니다.

## 📄 기타

추가적으로 전달하고 싶은 내용이나 특별한 요구 사항이 있으면 작성해 주세요.

playlist 라우팅들을 하나의 그룹으로 만들고 싶어서,
children으로 하위 라우팅들을 묶었는데, 라우팅 구조가 기존의 것과 조금 달라져서 각각으로 다 빼야 할지 고민입니다.

![스크린샷 2024-08-23 182703](https://github.com/user-attachments/assets/a6205a2d-2afc-46b6-b636-3fd80aa20cec)

보시면 
/playlist/likes
/playlist/saved
/playlist/:userId  <--- 플레이 리스트에 들어가면 id를 받아서 해당 플리 목록

이렇게 되어 있는데

현재는
/playlist/:userId <--- 위와 같습니다.
/playlist/:userId/likes
/playlist/:userId/saved

이런식으로 라우팅이 되고 있습니다.

2024-08-27 11:46 UTC, LfromTheE commented
> 기다리고 있던 라우팅이네요👍 근데 동혁님 리뷰어 설정과 파일 충돌 해결해주셔야 할 것 같습니다!

develop에서 다시 merge하고 커밋하도록 하고 다시 pr올리겠습니다.

2024-08-27 11:47 UTC, kimisadev27 requested changes

2024-08-27 11:47 UTC, kimisadev27 commented on src/router/router.tsx
> +        ) /*	following 페이지와 profile/following/:id 페이지의 다른점은? -> 그냥 following/:id로 통일?	*/,
# /following
![image](https://github.com/user-attachments/assets/030acb19-60d7-4ead-abb7-8b60fed4b382)

# /profile/following/:id
![image](https://github.com/user-attachments/assets/a34d9594-2bbe-475b-b39d-46e8e6498d66)

둘이 달라서 합치면 안됩니다!

2024-08-27 11:47 UTC, kimisadev27 commented on src/styles/GlobalStyles.tsx
develop 브랜치 merge하고 올려주세요~

2024-08-27 11:47 UTC, kimisadev27 commented on src/router/router.tsx
> +    path: '/',
path  constant로 빼주세요!

2024-08-27 11:47 UTC, kimisadev27 commented on src/router/router.tsx
> +        path: 'following/:id',
userid인지 playlistid인지 적어주세요

2024-08-27 12:34 UTC, LfromTheE commented on src/router/router.tsx
> +        ) /*	following 페이지와 profile/following/:id 페이지의 다른점은? -> 그냥 following/:id로 통일?	*/,
보시면
/playlist/likes
/playlist/saved
/playlist/:userId <--- 플레이 리스트에 들어가면 id를 받아서 해당 플리 목록

이렇게 되어 있는데

현재는
/playlist/:userId <--- 위와 같습니다.
/playlist/:userId/likes
/playlist/:userId/saved

이런식으로 라우팅이 되고 있습니다.


이 부분은 어떻게 생각하시나요? playlist를 children으로 묶지말고 따로 라우트를 팔까요?

2024-08-27 13:55 UTC, LfromTheE commented
path 전부 constant쪽으로 변경 및 이동했습니다.
 '/following'과 '/profile/following/:id'라우트 분기하였습니다.
 추가로 말씀하신 id => userId로 매개변수명 변경 하였습니다.

2024-08-27 14:12 UTC, kimisadev27 approved these changes

2024-08-27 15:35 UTC, dev-meryoung commented on src/.env
.env 파일이 같이 올라와서 다시 확인 부탁드립니다~!

2024-08-28 08:30 UTC, hyeppyy approved these changes

2024-08-28 08:33 UTC, kimisadev27 approved these changes

2024-08-28 08:33 UTC, kimisadev27 commented on src/component/TempFooter.tsx
constant로 빼셨는데 여기는 안하셨네요.. ㅜ

2024-08-28 08:36 UTC, merged